### ISSUE TITLE
node-gyp fails to build on Travis CI machine (Ubuntu 12.04.5 LTS)

### ISSUE THREAD

**Issue by miherlosev** [MayhemYDG/iltorb#18]
For more details see https://travis-ci.org/testcafe-build-bot/testcafe-hammerhead/jobs/175706806

```js
> iltorb@1.0.13 install /home/travis/build/testcafe-build-bot/testcafe-hammerhead/node_modules/iltorb

> node-gyp rebuild

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

gyp WARN download NVM_NODEJS_ORG_MIRROR is deprecated and will be removed in node-gyp v4, please use NODEJS_ORG_MIRROR

make: Entering directory `/home/travis/build/testcafe-build-bot/testcafe-hammerhead/node_modules/iltorb/build'

  CC(target) Release/obj.target/decode/brotli/common/dictionary.o

  CC(target) Release/obj.target/decode/brotli/dec/bit_reader.o

  CC(target) Release/obj.target/decode/brotli/dec/decode.o

  CC(target) Release/obj.target/decode/brotli/dec/huffman.o

  CC(target) Release/obj.target/decode/brotli/dec/state.o

  CXX(target) Release/obj.target/decode/src/common/allocator.o

In file included from ../src/common/allocator.cc:2:0:

../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler
```

**Comment by MayhemYDG** [comment]
`../../nan/nan.h:43:3: error: #error This version of node/NAN/v8 requires a C++11 compiler`

Travis doesn't have a C++11 compiler pre-installed. Check this repo's travis config to get an updated g++:
https://github.com/MayhemYDG/iltorb/blob/master/.travis.yml#L9-L17

**Comment by miherlosev** [comment]
Ok.
I think you can fallback to js implementation if appropriate compiler doesn't exists on target machine.
