### ISSUE TITLE
nopt not found since 1.3.1

### ISSUE THREAD

**Issue by JbIPS** [MayhemYDG/iltorb#38]
Hi,
I recently updated my dependencies and got an error from iltorb `1.3.2`:
```
[...]/node_modules/iltorb
> node-pre-gyp install --fallback-to-build

module.js:328
throw err;
^

Error: Cannot find module 'nopt'
at Function.Module._resolveFilename (module.js:326:15)
at Function.Module._load (module.js:277:25)
at Module.require (module.js:354:17)
at require (internal/module.js:12:17)
at Object.<anonymous> ([...]/node_modules/iltorb/node_modules/node-pre-gyp/lib/node-pre-gyp.js:14:12)
at Module._compile (module.js:410:26)
at Object.Module._extensions..js (module.js:417:10)
at Module.load (module.js:344:32)
at Function.Module._load (module.js:301:12)
at Module.require (module.js:354:17)
-a-native@1.5.2 install [...]/node_modules/lzma-native
> node-pre-gyp install --fallback-to-build
```

From your changelog I can't see what causes it but it works perfectly with `1.3.1`.

FYI, I'm using node `4.2.6` with npm `2.14.12`. Thank you!

**Comment by MayhemYDG** [comment]
That's interesting to say the least.
Can you try to update npm (`npm i -g npm`), and try to install iltorb again?

**Comment by JbIPS** [comment]
Updated to npm `5.0.4` and it worked. Now let's find the breaking version 😄 ! Which one are you using?

**Comment by MayhemYDG** [comment]
I'm on npm 5 as well, since I'm using node 8.

Your version of node is quite outdated, you definitely should update it as well, even if you stay at v4. https://nodejs.org/dist/latest-v4.x/

**Comment by JbIPS** [comment]
I totally agree, sadly I have some company restriction on the versions 😌.

Could you set the npm engine requirements so future users will know what do do?

Thank you
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by MayhemYDG** [comment]
That's a shame, does your company not care about security?

As for setting an npm version requirement, I'd need to know which npm version is working fine. 🤔

**Comment by JbIPS** [comment]
It looks OK with npm `3.0.0`. I think that's good enough 😉
